splash = false

wallpaper {
    monitor = DP-2
    #path = ~/Documents/wallpapers/wallpaper_one.png
    path = /mnt/4tb/_Projects/Wallpapers/wallpaper4/wallpaper.002.png
    fit_mode = cover
}

wallpaper {
    #monitor = HDMI-A-1
    monitor = HDMI-A-1
    #path = ~/Documents/wallpapers/wallpaper_one.png
    path = /mnt/4tb/_Projects/Wallpapers/wallpaper4/wallpaper.002.png
    fit_mode = cover
}
